title: "Katakam Prashanth"
description: ''' Detail-oriented analyst with 2 years of experience at Amazon, specializing in quality assurance and compliance within last-mile operations. Skilled in investigations, audits, and risk analysis, with a proven record of reducing defects and improving operational accuracy. Proficient in Python, SQL, Mongodb and analytical tools for workflow optimization and reporting. Experienced in SOP development, training, and cross-functional collaboration, with strong problem-solving, communication, and adaptability in fast-paced environments. '''
theme: jekyll-theme-primer

# clean URLs like /my-post/
permalink: /:title/

# allow manual excerpt breaks in posts with <!--more-->
excerpt_separator: "<!--more-->"

# (Optional) if you host under a project site, set baseurl; for user site, leave empty
# baseurl: ""
