title: "Katakam Prashanth"
description: ''
theme: jekyll-theme-primer
timezone: Asia/Kolkata

# clean URLs like /my-post/
permalink: /:title/

# allow manual excerpt breaks in posts with <!--more-->
excerpt_separator: "<!--more-->"

# (Optional) if you host under a project site, set baseurl; for user site, leave empty
# baseurl: ""
