title: "Katakam Prashanth"
description: "I build practical AI systems in RAG, CV, and data apps."
theme: jekyll-theme-primer

# clean URLs like /my-post/
permalink: /:title/

# allow manual excerpt breaks in posts with <!--more-->
excerpt_separator: "<!--more-->"

# (Optional) if you host under a project site, set baseurl; for user site, leave empty
# baseurl: ""
